const EmployeesData = [
    {
        firstName: 'Sergio',
        lastName: 'Pecores',
        dateOfBirth: '1981/03/25',
        street: '10 Golden Leaf Plaza',
        city: 'Miami',
        state: 'Florida',
        stateAbbrev: 'FL',
        zipCode: '32589',
        startDate: '2010/09/14',
        department: 'Sales',
    },
    {
        firstName: 'Séverine',
        lastName: 'Bizot',
        dateOfBirth: '2001/12/03',
        street: '71 avenue Lupin',
        city: 'LosAngeles',
        state: 'California',
        stateAbbrev: 'CA',
        zipCode: '75689',
        startDate: '2021/06/22',
        department: 'Engineering',
    },
    {
        firstName: 'Catherine',
        lastName: 'Grain',
        dateOfBirth: '1995/09/08',
        street: 'Long street',
        startDate: '2020/10/10',
        department: 'Sales',
        city: 'Auxerre',
        state: 'Alabama',
        stateAbbrev: 'AL',
        zipCode: 27950,
    },
    {
        firstName: 'Charles',
        lastName: 'Temeraire',
        startDate: '2002/12/29',
        department: 'Engineering',
        dateOfBirth: '1992/12/12',
        street: 'truc',
        city: 'Moulié',
        state: 'Alabama',
        stateAbbrev: 'AL',
        zipCode: 33500,
    },
    {
        firstName: 'Freddy',
        lastName: 'Kruger',
        startDate: '2004/04/24',
        department: 'Human Resources',
        dateOfBirth: '1968/08/18',
        street: 'astuce',
        city: 'Pingouse',
        state: 'Connecticut',
        stateAbbrev: 'CT',
        zipCode: 69520,
    },
    {
        firstName: 'Alfred',
        lastName: 'Limons',
        startDate: '2002/03/27',
        department: 'Engineering',
        dateOfBirth: '1995/01/20',
        street: 'rue mortis',
        city: 'Nimoubay',
        state: 'California',
        stateAbbrev: 'CA',
        zipCode: 14000,
    },
    {
        firstName: 'Bryan',
        lastName: 'ZieGler',
        startDate: '2006/11/20',
        department: 'Engineering',
        dateOfBirth: '1984/04/26',
        street: 'la rue pavée',
        city: 'New York',
        state: 'New York',
        stateAbbrev: 'NY',
        zipCode: 75000,
    },
    {
        firstName: 'Claire',
        lastName: 'Magdougal',
        startDate: '2019/09/02',
        department: 'Legal',
        dateOfBirth: '07/03/1997',
        street: 'rue Pasteur',
        city: 'Cheyennes',
        state: 'Colorado',
        stateAbbrev: 'CO',
        zipCode: 76800,
    },
    {
        firstName: 'Dan',
        lastName: 'Akroy',
        startDate: '2021/03/02',
        department: 'Sales',
        dateOfBirth: '1993/01/05',
        street: 'rue de la valléee chantante',
        city: 'Miami',
        state: 'Florida',
        stateAbbrev: 'FL',
        zipCode: 96880,
    },
    {
        firstName: 'Chris',
        lastName: 'Verdugo',
        startDate: '2012/11/10',
        department: 'Sales',
        dateOfBirth: '1975/08/03',
        street: 'rue Thomas Edison',
        city: 'Bilfilia',
        state: 'Virginia',
        stateAbbrev: 'VA',
        zipCode: 27200,
    },
    {
        firstName: 'Kevin',
        lastName: 'Bacon',
        startDate: '2019/10/01',
        department: 'Marketing',
        dateOfBirth: '1997/01/03',
        street: 'impasse de la bijouterie',
        city: 'Baton Rouge',
        state: 'Louisiana',
        stateAbbrev: 'LA',
        zipCode: 69850,
    },
    {
        firstName: 'Nora',
        lastName: 'Misdrawn',
        startDate: '2016/09/13',
        department: 'Human Resources',
        dateOfBirth: '1990/07/17',
        street: 'rue fleurie',
        city: 'Detroit',
        state: 'Michigan',
        stateAbbrev: 'MI',
        zipCode: 54200,
    },
    {
        firstName: 'Lavinia',
        lastName: 'Cohen',
        startDate: '2015/02/28',
        department: 'Marketing',
        dateOfBirth: '1989/01/23',
        street: 'rue du Texas',
        city: 'Texas',
        state: 'Texas',
        stateAbbrev: 'TX',
        zipCode: 98650,
    },
    {
        firstName: 'Marie',
        lastName: 'Cure',
        startDate: '2012/04/30',
        department: 'Legal',
        dateOfBirth: '1992/05/05',
        street: 'rue cajun',
        city: 'Limody',
        state: 'Nebraska',
        stateAbbrev: 'NE',
        zipCode: 17320,
    },
    {
        firstName: 'Freya',
        lastName: 'Wyatt',
        startDate: '2022/08/22',
        department: 'Sales',
        dateOfBirth: '2022/12/03',
        street: '7771 Lotus. Ave',
        city: 'Austin',
        state: 'Wyoming',
        zipCode: '77706',
    },
    {
        firstName: 'Tobias',
        lastName: 'Hull',
        startDate: '2022/09/29',
        department: 'Marketing',
        dateOfBirth: '2022/08/18',
        street: 'P.O. Box 915, 2109 Faucibus St.',
        city: 'Dover',
        state: 'Massachusetts',
        zipCode: '68261',
    },
    {
        firstName: 'Alma',
        lastName: 'Barton',
        startDate: '2022/06/08',
        department: 'Human Ressources',
        dateOfBirth: '2002/05/02',
        street: 'Ap #613-9371 Phasellus St.',
        city: 'Las Vegas',
        state: 'Oregon',
        zipCode: '52067',
    },
    {
        firstName: 'Amos',
        lastName: 'Villarreal',
        startDate: '03/24/2022',
        department: 'Marketing',
        dateOfBirth: '2008/03/23',
        street: 'P.O. Box 498, 4947 Fusce Rd.',
        city: 'Cedar Rapids',
        state: 'Illinois',
        zipCode: '66452',
    },
    {
        firstName: 'Gavin',
        lastName: 'Conrad',
        startDate: '2021/11/27',
        department: 'Legal',
        dateOfBirth: '1989/11/23',
        street: '446-3137 A Av.',
        city: 'Tuscaloosa',
        state: 'Vermont',
        zipCode: '33235',
    },
    {
        firstName: 'Quail',
        lastName: 'Jefferson',
        startDate: '2021/12/24',
        department: 'Marketing',
        dateOfBirth: '2002/09/22',
        street: '488-5504 Purus. Av.',
        city: 'Minneapolis',
        state: 'Tennessee',
        zipCode: '28504',
    },
    {
        firstName: 'Robert',
        lastName: 'Dalton',
        startDate: '2022/08/20',
        department: 'Marketing',
        dateOfBirth: '2001/06/05',
        street: '824-5978 Cursus Road',
        city: 'Auburn',
        state: 'Mississippi',
        zipCode: '18285',
    },
    {
        firstName: 'Alec',
        lastName: 'Key',
        startDate: '2022/01/25',
        department: 'Sales',
        dateOfBirth: '1992/01/22',
        street: 'Ap #140-355 Nibh. Avenue',
        city: 'Cheyenne',
        state: 'Vermont',
        zipCode: '28371',
    },
    {
        firstName: 'Malik',
        lastName: 'Rocha',
        startDate: '2022/01/23',
        department: 'Sales',
        dateOfBirth: '1992/08/25',
        street: 'Ap #293-4948 Vulputate Road',
        city: 'Rockford',
        state: 'Michigan',
        zipCode: '60004',
    },
    {
        firstName: 'Chloe',
        lastName: 'Grimes',
        startDate: '2022/03/26',
        department: 'Marketing',
        dateOfBirth: '2000/01/01',
        street: '813-7640 Purus. Rd.',
        city: 'Lincoln',
        state: 'Colorado',
        zipCode: '32532',
    },
    {
        firstName: 'Daquan',
        lastName: 'Mcdowell',
        startDate: '2022/08/13',
        department: 'Legal',
        dateOfBirth: '1995/02/01',
        street: '149-8462 Accumsan Rd.',
        city: 'Bloomington',
        state: 'Colorado',
        zipCode: '45144',
    },
    {
        firstName: 'Mariko',
        lastName: 'Underwood',
        startDate: '02/07/2023',
        department: 'Engineering',
        dateOfBirth: '2001/10/04',
        street: '934-8620 Eu, Road',
        city: 'Louisville',
        state: 'Vermont',
        zipCode: '44593',
    },
    {
        firstName: 'Selma',
        lastName: 'Duran',
        startDate: '2022/09/24',
        department: 'Engineering',
        dateOfBirth: ' 2003/10/02',
        street: 'Ap #397-9861 Velit Ave',
        city: 'Saint Paul',
        state: 'Mississippi',
        zipCode: '71453',
    },
]

export default EmployeesData
